site:
  title: Federation Tier with AQL
  start_page: federation-aql::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
output:
  dir: build/site
runtime:
  log:
    failure_level: warn
